openzipkin/zipkin-php

src/Zipkin/Annotation.php, src/Zipkin/NoopSpan.php, src/Zipkin/RealSpan.php, src/Zipkin/Recorder.php, src/Zipkin/Span.php
For the sake of convenience, the `$timestamp` parameter becomes optional, making it `Timestamp\now()` its default value same as `brave`.
Ping @beberlei
=> Makes timestamp optional on Span::finish.

src/Zipkin/Propagation/B3.php, src/Zipkin/Propagation/DefaultSamplingFlags.php, src/Zipkin/Propagation/SamplingFlags.php, src/Zipkin/Propagation/TraceContext.php, tests/Integration/Reporters/Http/CurlFactoryTest.php, tests/Unit/NoopSpanTest.php, tests/Unit/Propagation/B3Test.php, tests/Unit/Propagation/TraceContextTest.php
This PR fixes a couple of details in order to make consistent the creation of new traces using `nextSpan`.
Ping @cc5092
=> Final tweaks on the TraceContext and SamplingFlags.

src/Zipkin/Reporters/Http.php
Currently we catch any reporting exception and drop a log record for it but following most common approach we should propagate the exception and let the client decide what to do with it (ex. ignore the error, send a metric, etc.). This PR is not a breaking change but could break clients not doing `try/catch` when reporting.
Ping @adriancole @cc5092 @felixfbecker
=> Removes try/catch in HTTP reporter.

.travis.yml, src/Zipkin/Reporters/Http.php, src/Zipkin/Reporters/InMemoryMetrics.php, src/Zipkin/Reporters/Metrics.php, src/Zipkin/Reporters/NoopMetrics.php, tests/Unit/Reporters/HttpMockFactory.php, tests/Unit/Reporters/HttpTest.php, tests/Unit/Reporters/InMemoryMetricsTest.php, tests/Unit/Reporters/NoopMetricsTest.php, tests/Unit/Reporters/NoopTest.php
This PR adds the interface for reporter metrics. Reporter metrics is the contract for handling with reporting failures (for example: server not available, failure over network, etc.)
The reason for https://github.com/jcchavezs/zipkin-php/compare/adds_support_for_reporter_metrics?expand=1#diff-542892a2dd974b841a279a65f6b8c93aR35 is to keep retro compatibility.
Ping @adriancole @eligijusvitkauskas-home24  @cc5092
Closes #64
=> Adds support for reporter metrics.

src/Zipkin/Recording/SpanMap.php, tests/Unit/Recording/SpanMapTest.php
Change \Zipkin\Recording\SpanMap::getHash() to crc32() to reduce hash collisions.
As discussed in https://github.com/jcchavezs/zipkin-php/issues/76, spl_object_hash() can produce hash collisions when the PHP garbage collectors cleans up destroyed spans.
This changes the getHash() function from spl_object_hash() to a crc32() hash of the spanId, traceId and parentId.
=> Change SpanMap::getHash() to crc32() to reduce hash collisions

src/Zipkin/Reporters/Http/CurlFactory.php, tests/Integration/Reporters/Http/CurlFactoryTest.php
So that the string value of the transfer is returned rather than outputting it directly.
=> Set CURLOPT_RETURNTRANSFER to true 

phpunit.xml
This PR
💁‍♂️ This way it will always refer to the appropriate schema.
=> Enhancement: Reference phpunit schema as installed with composer

README.md
I just spent a few hours debugging code that wasn't forwarding B3 headers.
Turns out I copy/pasted the headers from the README, which used a non standard dash character that PHP wasn't able to parse.
Hopefully this will prevent other folks to lose time with this as well!
=> Fix dash characters in README

src/Zipkin/Endpoint.php
This PR actually just does one minor thing, but it actually preserves compatibility with jaegers' implementation of their Zipkin Gateway. 
Their struct requires and endpoint port to be an integer. Although the create method for the `Endpoint`  is typed correctly, `REMOTE_PORT` is still a string when fetched through `$_SERVER`:
```php
["REMOTE_PORT"]=>
string(5) "51124"
```
Jaeger zipkin struct: https://github.com/jaegertracing/jaeger/blob/50429cb55aee9280e39621a0b5aae3c2afe5d190/cmd/collector/app/zipkin/json.go#L35
I was not sure on how to fit tests for this. Does any of the maintainers have a clue on this?
=> Endpoint createFromGlobals should create using an integer port

src/Zipkin/Reporters/Http/CurlFactory.php
Generally speaking, the Zipkin reporting call should be non-blocking and asynchronous.  But since PHP almost doesn't have either of these properties, it's good to at least be sure that reporting of the Zipkin Trace is not causing a major delay in sampled traces.
Closes #94
=> Allow a timeout value to be set on the cURL Call.

README.md
* Changes installation instructions to go with current version of this package
* Changes downloads badge to use current version of this package
Seems that this may have gotten missed when moving to new organization ( 8f8458b484277c672b0c82b67b27d4f8da52c284 , 8db5b0444cd73d42cfc3070b982e5e3a166398c7 , etc)
=> Fix organization references in readme

src/Zipkin/TracingBuilder.php
`Endpoint::withServiceName` will return a new instance of Endpoint, so when endpoint is null, service name is invalid.
=> fix if endpoint is null, than service name is invalid

src/Zipkin/NoopSpan.php, src/Zipkin/Propagation/CurrentTraceContext.php, src/Zipkin/RealSpan.php, src/Zipkin/Recorder.php, src/Zipkin/Recording/SpanMap.php, src/Zipkin/Reporters/Http/CurlFactory.php, src/Zipkin/Span.php, src/Zipkin/Tracer.php, src/Zipkin/TracingBuilder.php, tests/Unit/DefaultTracingTest.php, tests/Unit/NoopSpanTest.php, tests/Unit/Propagation/CurrentTraceContextTest.php, tests/Unit/RealSpanTest.php, tests/Unit/Recording/SpanMapTest.php, tests/Unit/TracerTest.php, tests/Unit/TracingBuilderTest.php
One point people makes is usually the fact that we use static constructors in cases where it merely calls the constructor. This PR gets rid of those constructors.
=> chore: removes static constructors when unnecessary.

src/Zipkin/Propagation/Map.php, tests/Unit/Propagation/MapTest.php
Map getter is often used as http headers getter, mostly because frameworks and libraries like symfony still don't use the PSR request/response objects (i.e. the official ones), thus Request getter can't be used and map is the way to go (e.g. https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/src/ZipkinBundle/Middleware.php#L60).
Main thing with Map is that it is not supposed to be key case insensitive, however when we write into a map, we use lowercase key (see https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Propagation/Map.php#L42) and when we get we also use the the lower case key (see https://github.com/openzipkin/zipkin-php/blob/master/src/Zipkin/Propagation/Map.php#L19). This is mainly to fulfill the use case described in the previous paragraph. …
=> chore: makes lookup for Map getter to be case insensitive (#137).

src/Zipkin/NoopSpan.php, src/Zipkin/NoopSpanCustomizer.php, src/Zipkin/RealSpan.php, src/Zipkin/SpanCustomizer.php, src/Zipkin/SpanCustomizerShield.php, tests/Unit/NoopSpan.php, tests/Unit/SpanCustomizerShieldNoopSpan.php, tests/Unit/SpanCustomizerShieldTest.php
This PR introduces the new concept of `SpanCustomizer` which is a port from brave and it is a needed abstractions for upcoming improvements to the library: inSpan and HTTP client/server PSR implementation.
=> Adds span customizer

README.md, phpstan.neon, src/Zipkin/Reporters/Http.php, tests/Unit/Reporters/HttpTest.php
https://github.com/openzipkin/zipkin-php/commit/c81026ae32ffd70771d3a5b994d2cec0feedba74#diff-542892a2dd974b841a279a65f6b8c93a introduced a breaking change in the constructor of the HTTP reporter, while the change makes sense we don't want apps to break apps. This PR fixes the retro compatibility issue so transition to v2 is smoother.
=> chore: fixes retrocompatibility of the HTTP reporter constructor

src/Zipkin/Reporters/Http.php, tests/Unit/Reporters/HttpTest.php
Because https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/3771647/src/ZipkinBundle/TracingFactory.php#L65 which we will fix in origin but this means people could have done the same.
=> chore: accept null for the first parameter in the HTTP reporter.

src/Zipkin/Propagation/RequestHeaders.php, tests/Unit/Propagation/RequestHeadersTest.php
This PR fixes a misleading behaviour of the method `RequestHeaders::put` as we were actually appending instead of overriding.
=> fix: RequestHeaders setter puts the value, overriding it if already exists.

src/Zipkin/Propagation/TraceContext.php, tests/Unit/TracerTest.php
Currently we mistakenly allowed users to pass the `usesTraceId128bits` value which was misleading because it could happen the traceId was 64bit but we passed usesTraceId128bits = true. This was a bug and it is safe to remove as a) in case someone actually cares about the value of TraceContext::usesTraceId128bits, the value was misleading and b) even if someone was passing the value on the `TraceContext::create` method, PHP does not fail if you pass an additional argument.
=> fix: removes usesTraceId128bits from signature an infer from the traceId length.

README.md, src/Zipkin/Propagation/ServerHeaders.php, tests/Unit/Propagation/ServerHeadersTest.php
If you don't have access to a Request object, it's convenient to extract the headers from the global $_SERVER variable.
=> Support extracting incoming headers from the $_SERVER variable

src/Zipkin/Propagation/Map.php
Although not ideal, this implementation is more efficient as it only iterates the array until it is needed instead of changing the case for the full array every time.
=> fix(propagation): fixes map lookup for case insensitiviness.

src/Zipkin/Propagation/DefaultSamplingFlags.php, src/Zipkin/Propagation/SamplingFlags.php, src/Zipkin/Propagation/TraceContext.php, src/Zipkin/Tracer.php
Currently there it is only possible to override the sampling decision for trace context but not for sampling flags. This formalizes the use case to override the sampling in the SamplingFlags interface.
The use case is the popular "requestSampler" which changes the sampler decision based on a request (both for client and server).
The use case is in the usage of `Tracer::nextSpanWithSampler` as used in https://github.com/jcchavezs/zipkin-instrumentation-symfony/pull/70/files#diff-46b82fded07ac22b103293cbc8c3ebbeR60-R63
=> feat(sampling-flags): adds withSampled method for SamplingFlags.

src/Zipkin/DefaultTracing.php, src/Zipkin/Recording/Span.php, src/Zipkin/Tracer.php, src/Zipkin/TracingBuilder.php, tests/Unit/TracingBuilderTest.php
This will let me implement "firehose mode", similar to what we have in
py_zipkin.
Basically what I need is a way to call 2 different Reporters:
- one gets called only when sampled is True
- one gets called every time (this is the firehose recorder)
This cannot be accomplished with just one Reporter, because once we're
inside the reporter we've lost any info on whether the trace was sampled
or not.
I can almost do this in zipkin-php, there are only 2 things missing.
- if sampled is False, we create a NoopSpan. So I need an extra flag to
inform the tracer that I always want to create a RealSpan
- the Recorder is hardcoded inside the Tracer class, so I cannot pass my
own.
Once those 2 things are supported, I can write my own Recorder subclass
that calls the right Reporters as needed with …
=> Allow using custom Recorder and add option to always record spans

src/Zipkin/Propagation/B3.php, src/Zipkin/Propagation/DefaultSamplingFlags.php, src/Zipkin/Propagation/TraceContext.php, src/Zipkin/Tracer.php, tests/Unit/Propagation/B3Test.php, tests/Unit/Propagation/DefaultSamplingFlagsTest.php, tests/Unit/Propagation/TraceContextTest.php
From now on, debug=true will force a sampled=true value in the TraceContext, making it easier for users to just check $context->isSampled() instead of also checking the $context->isDebug().
=> fix(propagation): fixes logic around sampling and debug to improve the API usability.

src/Zipkin/Instrumentation/Http/Client/Psr18/Request.php, src/Zipkin/Instrumentation/Http/Client/Psr18/Response.php, src/Zipkin/Instrumentation/Http/Client/Request.php, src/Zipkin/Instrumentation/Http/Client/Response.php, src/Zipkin/Instrumentation/Http/Request.php, src/Zipkin/Instrumentation/Http/Response.php, src/Zipkin/Instrumentation/Http/Server/Psr15/Request.php, src/Zipkin/Instrumentation/Http/Server/Psr15/Response.php, src/Zipkin/Instrumentation/Http/Server/Request.php, src/Zipkin/Instrumentation/Http/Server/Response.php, tests/Unit/Instrumentation/Http/Client/Psr18/RequestTest.php, tests/Unit/Instrumentation/Http/Client/Psr18/ResponseTest.php, tests/Unit/Instrumentation/Http/Server/Psr15/RequestTest.php, tests/Unit/Instrumentation/Http/Server/Psr15/ResponseTest.php
This PR covers the Request/Response value objects for client and server abstractions. It also makes it open the return type for `Response::getRequest` so the extending classes can decide.
=> tests(http): covers http client/server request/response.

src/Zipkin/Instrumentation/Http/Client/Psr18/Request.php, src/Zipkin/Instrumentation/Http/Client/Psr18/Response.php, src/Zipkin/Instrumentation/Http/Server/Psr15/Request.php, src/Zipkin/Instrumentation/Http/Server/Psr15/Response.php
This adds type guards on the return type and it is convenient as these classes are final.
=> chore(http): adds return type for PSR parsing request and response.

src/Zipkin/Reporters/JsonV2Serializer.php, tests/Unit/Reporters/HttpTest.php, tests/Unit/Reporters/JsonV2SerializerTest.php
Somehow we missed that the swagger definition for the post spans endpoint was requiring the span name and the service name to be lowercase. Since this is purely zipkin json v2, we delegate this responsability to the JSON V2 Serializer.
https://zipkin.io/zipkin-api/\#/default/post_spans.
=> feat(json-format): lowercase span name and service name as per swagger definition

README.md
On README.md some code lines missing semicolon.
=> docs: fixes missing semicolon on readme sample

src/Zipkin/Reporters/Http/ClientFactory.php, src/Zipkin/Reporters/Http/CurlFactory.php, tests/Integration/Reporters/Http/CurlFactoryTest.php
Related to https://github.com/openzipkin/b3-propagation/pull/42#event-3760887270
=> chore(reporting): adds b3:0 header to the reporting call to avoid tracing from mesh sidecars

src/Zipkin/Reporters/JsonV2Serializer.php, tests/Unit/Reporters/JsonV2SerializerTest.php
Currently tags aren't being escaped and serialization was failing when adding json payloads as tags or multiline values. This is specially useful when recording request/response payloads.
Ping @adriancole @kotharironak
=> fix(json-serializer): fixes the JSON serialization to escape quotes on tags

src/Zipkin/Instrumentation/Http/Server/DefaultHttpServerParser.php, src/Zipkin/Instrumentation/Http/Server/Psr15/Response.php, src/Zipkin/Instrumentation/Http/Server/Response.php, tests/Unit/Instrumentation/Http/Server/BaseResponseTest.php, tests/Unit/Instrumentation/Http/Server/Psr15/ResponseTest.php
This PR adds support for including the route for late parsing, mostly for those frameworks where the route is not available until very late in the request/response lifecycle (e.g. symfony).
e.g. https://github.com/jcchavezs/zipkin-instrumentation-symfony/blob/master/src/ZipkinBundle/KernelListener.php#L218
=> feat(http): adds support for route in response object for late parsing.

tests/Unit/Instrumentation/Http/Server/BaseResponseTest.php, tests/Unit/Instrumentation/Http/Server/Psr15/ResponseTest.php
Currently the base test was not comparing the response route.
=> tests: adds support for the rout e in the HTTP response.

.github/workflows/ci.yml, .gitignore, composer.json, phpstan.neon, phpunit.xml, src/Zipkin/Instrumentation/Http/Client/Psr18/README.md, tests/Unit/Instrumentation/Http/Client/Psr18/ClientTest.php, tests/Unit/Instrumentation/Http/Client/Psr18/RequestTest.php, tests/Unit/Instrumentation/Http/Client/Psr18/ResponseTest.php, tests/Unit/Instrumentation/Http/Server/Psr15/MiddlewareTest.php, tests/Unit/Instrumentation/Http/Server/Psr15/RequestTest.php, tests/Unit/Instrumentation/Http/Server/Psr15/ResponseTest.php, tests/Unit/Propagation/RequestHeadersTest.php, tests/Unit/Propagation/TraceContextTest.php, tests/Unit/RealSpanTest.php, tests/Unit/RecorderTest.php, tests/Unit/Reporters/HttpTest.php, tests/Unit/TracerTest.php
Proposal for issue #202 
- there was a bit of a snowball there with respect to aligning dependencies to work with minor PHP versions (I did not try too hard to find a way to keep 7.2 as per issue comments).
-  See https://github.com/php-http/discovery/issues/164 - guzzlehttp doesn't provide expected PSR-17 factories (there's code available ready for their v2, but that would mean dropping some stability constraints) => switched to nyholm (it claims some performance boost as well, though probably not too relevant since we're talking tests)
- some tweaks around the tests: eg `dechex()` needs an `int`, but `hexdec()` returns `int|float`, running afoul of strong type check.
- updated phpunit also due to version constraints (phpunit 8 was still complaining about running on php 8) which led to …
=> PHP 8: upgrade middlewares, phpunit and replace guzzle psr7 with nyholm

src/Zipkin/Reporters/Http.php, tests/Unit/Reporters/HttpTest.php
This PR polish the constructor's signature for HTTP reporter and finally drops 1.x compatibility.
=> chore(http-reporter): removes retrocompatibility constructor signature.

phpstan.neon, tests/Unit/Reporters/MemcachedTest.php
based on discussion here #206. it work for windows now (missing ext-memcached). 
the ubuntu failure related to coverall
=> Fix build if ext-memcached is missing

composer.json, src/Zipkin/Instrumentation/Http/Request.php, src/Zipkin/Instrumentation/Http/Response.php
This is needed because we can't do any guarantee about the types of underlying request/response models, e.g. in PSR we would use an object but in Symfony Client it is most likely be an array (see https://github.com/symfony/contracts/blob/v2.4.0/HttpClient/HttpClientInterface.php#L86), hence removing the optional object constraint.
=> Removes return type unwrap

.github/workflows/ci.yml, composer.json, src/Zipkin/Instrumentation/Mysqli/Mysqli.php, tests/Integration/Instrumentation/Mysqli/MysqliTest.php
This PR fixes the coverage value as currently it is misleading.
The reason for this coverage value is that we were running 
```
"test": [
"@test-unit",
"@test-integration"
],
```
So first target `test-unit` generated a report and then `test-integration` was overriding it and hence giving a false value.
=> Fixes coverage

README.md
```
Argument 2 passed to Zipkin\\RealSpan::tag() must be of the type string, int given
```
=>  Zipkin\\RealSpan::tag() must be of the type string
