- src/Zipkin/RealSpan.php
- tests/Unit/RealSpanTest.php
This fixes the remote endpoint infinite loop
Closes #7 
Ping @beberlei
> [#7] Fixes infinite loop when setting remote endpoint.

- src/Zipkin/Endpoint.php
- tests/Unit/EndpointTest.php
> [#6] Fixes warnings when creating and endpoint from globals in a CLI.

- src/Zipkin/Endpoint.php
- tests/Unit/EndpointTest.php
> [#5] Makes endpoint ipv4 parameter optional.

- src/Zipkin/NoopSpan.php
- src/Zipkin/Tracer.php
- tests/Unit/DefaultTracingTest.php
- tests/Unit/TracerTest.php
This PR changes the NoopSpan in order to return a valid TraceContext.
> Changes the NoopSpan in order to return a TraceContext on getContext.

- src/Zipkin/Propagation/B3.php
- tests/Unit/Propagation/B3Test.php
This change is based on https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/B3Propagation.java#L114
> Fixed the logic to extract context for B3.

- src/Zipkin/Annotation.php
> Removes V1 annotations and clarify the values for Span::kind.

- src/Zipkin/NoopSpan.php
- src/Zipkin/RealSpan.php
- src/Zipkin/Span.php
> Fixes TraceKeys reference.

- README.md
- src/Zipkin/Propagation/Map.php
- src/Zipkin/Propagation/RequestHeaders.php
- src/Zipkin/Propagation/Setter.php
- src/Zipkin/Recorder.php
- tests/Unit/Propagation/RequestHeadersTest.php
> Fixes readme

- src/Zipkin/DefaultTracing.php
- src/Zipkin/TraceContext.php
- src/Zipkin/Tracer.php
- tests/Unit/TraceContextTest.php
- tests/Unit/TracerTest.php
spanId will set by parentId and it will be null when it is root span
> wrong parameter usage. 

- src/Zipkin/Propagation/B3.php
- src/Zipkin/Propagation/Propagation.php
This fixes a problem when propagation carrier is an array and not an object.
> Fixes propagation in array.

- README.md
- src/Zipkin/DefaultTracing.php
- src/Zipkin/NoopSpan.php
- src/Zipkin/Propagation/B3.php
- src/Zipkin/Propagation/CurrentTraceContext.php
- src/Zipkin/Propagation/DefaultSamplingFlags.php
- src/Zipkin/Propagation/SamplingFlags.php
- src/Zipkin/Propagation/TraceContext.php
- src/Zipkin/RealSpan.php
- src/Zipkin/Recorder.php
- src/Zipkin/Recording/Span.php
- src/Zipkin/Recording/SpanMap.php
- src/Zipkin/Span.php
- src/Zipkin/Tracer.php
- src/Zipkin/TracingBuilder.php
- tests/Unit/DefaultTracingTest.php
- tests/Unit/Propagation/B3Test.php
- tests/Unit/Propagation/CurrentTraceContextTest.php
- tests/Unit/Propagation/TraceContextTest.php
- tests/Unit/RealSpanTest.php
- tests/Unit/RecorderTest.php
- tests/Unit/Recording/SpanMapTest.php
- tests/Unit/Recording/SpanTest.php
- tests/Unit/TracerTest.php
- tests/Unit/TracingBuilderTest.php
This PR adds support for `CurrentTraceContext`.
Ping @adriancole @beberlei @felixbecker @cc5092
Closes #29
> [#29] Adds support for CurrentTraceContext in tracer.

- .coveralls.yml
- .travis.yml
- README.md
- phpunit.xml
- tests/Unit/DefaultTracingTest.php
- tests/Unit/EndpointTest.php
- tests/Unit/Propagation/TraceContextTest.php
- tests/Unit/Recording/SpanMapTest.php
> Adds Coverage report.

- src/Zipkin/Propagation/B3.php
- src/Zipkin/Propagation/DefaultSamplingFlags.php
- src/Zipkin/Propagation/Propagation.php
- src/Zipkin/Propagation/SamplingFlags.php
- src/Zipkin/Propagation/TraceContext.php
- tests/Unit/Propagation/B3Test.php
- tests/Unit/Propagation/TraceContextTest.php
This PR changes the extractor interface.
Closes #43
> [#43] Changes the extractor interface.

- composer.json
- src/Zipkin/Reporters/Http/CurlFactory.php
- tests/Integration/Reporters/Http/CurlFactoryTest.php
This PR adds an integration test for the cURL HTTP reporter.
Ping @beberlei @felixfbecker
> Adds cURL integration test.

- composer.json
- src/Zipkin/Propagation/Id.php
- src/Zipkin/Propagation/TraceContext.php
- src/Zipkin/Sampler.php
- tests/Unit/Propagation/IdTest.php
Test the Id generation and validation.
> Adds tests for Ids.

- src/Zipkin/Propagation/Id.php
- tests/Unit/Propagation/IdTest.php
This PR makes the validation rules more flexible for `spanId` and `traceId`.
> [#52] Adds more flexible rules for Id validations.

- src/Zipkin/Tags.php
This PR adds small documentation for tags.
Ping @adriancole @basvanbeek
> Adds documentation to tags.

- src/Zipkin/RealSpan.php
- src/Zipkin/Timestamp.php
- tests/Unit/RealSpanTest.php
- tests/Unit/TimestampTest.php
This PR adds tests for timestamp.
> Adds tests for timestamp.

- codecov.yml
- src/Zipkin/Samplers/PercentageSampler.php
- tests/Unit/RealSpanTest.php
- tests/Unit/Samplers/BinarySamplerTest.php
This PR fixes a namespace problem with the `PercentageSampler`.
> Adds sampler test and renamed PercentageSampler namespace.

- src/Zipkin/Tags.php
From https://github.com/openzipkin/zipkin/pull/1943
> Adds http.route tag

- src/Zipkin/Propagation/B3.php
- src/Zipkin/Propagation/Exceptions/InvalidTraceContextArgument.php
- src/Zipkin/Propagation/TraceContext.php
- tests/Unit/Propagation/TraceContextTest.php
Based https://github.com/openzipkin/brave/issues/625 and  https://github.com/openzipkin/brave/pull/627
> Guards for not to fail when receiving malformed trace information.

- composer.json
- tests/Integration/Reporters/Http/CurlFactoryTest.php
This PR uses the new version of the httptest library which hides completely the forking of process.
> Updates httptest library with simpler tests.

- README.md
Current documentation was misleading in terms of how injection was supposed to be used.
Ping @tuber
Fixes #98
> docs: fixes documentation for injection

- composer.json
- tests/Integration/Reporters/Http/CurlFactoryTest.php
- tests/Unit/DefaultTracingTest.php
- tests/Unit/EndpointTest.php
- tests/Unit/NoopSpanTest.php
- tests/Unit/Propagation/B3Test.php
- tests/Unit/Propagation/CurrentTraceContextTest.php
- tests/Unit/Propagation/IdTest.php
- tests/Unit/Propagation/MapTest.php
- tests/Unit/Propagation/RequestHeadersTest.php
- tests/Unit/Propagation/TraceContextTest.php
- tests/Unit/RealSpanTest.php
- tests/Unit/RecorderTest.php
- tests/Unit/Recording/SpanMapTest.php
- tests/Unit/Recording/SpanTest.php
- tests/Unit/Reporters/HttpTest.php
- tests/Unit/Reporters/InMemoryMetricsTest.php
- tests/Unit/Reporters/InMemoryTest.php
- tests/Unit/Reporters/NoopMetricsTest.php
- tests/Unit/Reporters/NoopTest.php
- tests/Unit/Samplers/BinarySamplerTest.php
- tests/Unit/TimestampTest.php
- tests/Unit/TracerTest.php
- tests/Unit/TracingBuilderTest.php
This PR changes the classname for php unit test case as step towards PHP 7.
> chore: changes phpunit classname as a previous step towards PHPUnit 7.

- tests/Unit/Reporters/HttpMockFactory.php
- tests/Unit/Reporters/HttpTest.php
> fix: adds early return when the array of spans is empty.

- src/Zipkin/Reporters/Http.php
This one does the trick in v1. cc @caozhipan
> Fix empty spans

- appveyor.yml
This PR changes the current appveyor setup in order to use @ChadSikorra script, decreasing the CI times dramatically and it is way less error prone than the previous approach.
> chore: improves appveyor config.

- src/Zipkin/Endpoint.php
- src/Zipkin/Propagation/B3.php
- src/Zipkin/Propagation/Exceptions/InvalidPropagationCarrier.php
- src/Zipkin/Propagation/Exceptions/InvalidTraceContextArgument.php
- src/Zipkin/Propagation/Id.php
- src/Zipkin/Propagation/Map.php
- src/Zipkin/Propagation/RequestHeaders.php
- src/Zipkin/RealSpan.php
- src/Zipkin/Recording/Span.php
- src/Zipkin/Recording/SpanMap.php
- src/Zipkin/Reporters/Http.php
- src/Zipkin/Reporters/Http/CurlFactory.php
- src/Zipkin/Reporters/InMemory.php
- src/Zipkin/Samplers/PercentageSampler.php
- src/Zipkin/Timestamp.php
Reproduce with:
php php-cs-fixer --rules=native_function_invocation fix src --allow-risky=yes
(php-cs-fixer from : https://cs.symfony.com/)
Details:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
> Automated native_function_invocation fixes

- README.md
- src/Zipkin/Reporters/Http.php
- tests/Unit/Reporters/HttpTest.php
BREAKING CHANGE: This change is going to be introduced in 2.0
> Changes reporter

- src/Zipkin/Samplers/PercentageSampler.php
> fix: Correct inaccurate expression

- README.md
- composer.json
- phpstan.neon
- src/Zipkin/SpanName.php
- src/Zipkin/Tracer.php
- tests/Integration/Reporters/Http/CurlFactoryTest.php
- tests/Unit/InSpan/Callables.php
- tests/Unit/InSpan/Sumer.php
- tests/Unit/InSpanCallables.php
- tests/Unit/TracerTest.php
This PR finally tackles #115 and adds the SpanCustomizer interface, allowing to do further customizations in http tracing.
Most important code: https://github.com/openzipkin/zipkin-php/pull/128/files#diff-ced4309e6e2dfd1e487df57084f07566R233
Ping carefully @adriancole
> feat: adds inSpan and SpanCustomizer.

- src/Zipkin/DefaultTracing.php
- src/Zipkin/Propagation/B3.php
- src/Zipkin/Propagation/Propagation.php
- src/Zipkin/Propagation/TraceContext.php
- src/Zipkin/Recording/Span.php
- src/Zipkin/Recording/SpanMap.php
- src/Zipkin/Tracer.php
- src/Zipkin/TracingBuilder.php
- tests/Unit/DefaultTracingTest.php
- tests/Unit/Propagation/TraceContextTest.php
- tests/Unit/TracingBuilderTest.php
This PR adds support for joint spans.
cc @drolando @adriancole
> feat(join-spans): adds support for join-spans.

- src/Zipkin/Recording/Span.php
- src/Zipkin/Reporters/Http.php
- tests/Unit/Recording/SpanTest.php
- tests/Unit/Reporters/HttpTest.php
- tests/Unit/TracerTest.php
> tests(join-spans): adds tests for shared value in joinSpan.

- phpstan.neon
- src/Zipkin/DefaultErrorParser.php
- src/Zipkin/Endpoint.php
- src/Zipkin/ErrorParser.php
- src/Zipkin/Instrumentation/Http/Client/Client.php
- src/Zipkin/Instrumentation/Http/Client/DefaultParser.php
- src/Zipkin/Instrumentation/Http/Client/Parser.php
- src/Zipkin/NoopSpan.php
- src/Zipkin/RealSpan.php
- src/Zipkin/Recorder.php
- src/Zipkin/Recording/ReadbackSpan.php
- src/Zipkin/Recording/Span.php
- src/Zipkin/Recording/SpanMap.php
- src/Zipkin/Reporters/Http.php
- src/Zipkin/Reporters/JsonV2Serializer.php
- src/Zipkin/Reporters/SpanSerializer.php
- src/Zipkin/Span.php
- src/Zipkin/Tracer.php
- tests/Unit/DefaultErrorParserException.php
- tests/Unit/DefaultErrorParserTest.php
- tests/Unit/Instrumentation/Http/Client/ClientTest.php
- tests/Unit/Propagation/JsonV2SerializerTest.php
- tests/Unit/Reporters/HttpTest.php
- tests/Unit/SpanCustomizerShieldSpan.php
- tests/Unit/TracerTest.php
This PR adds support for span.error.
> feat(span-error): adds support for span error.

- src/Zipkin/Reporters/JsonV2Serializer.php
- tests/Unit/Propagation/JsonV2SerializerTest.php
> fix(json-serializer): fixes the kind in the json serializer.

- .github/workflows/ci.yml
- tests/Integration/Reporters/Http/CurlFactoryTest.php
- tests/Unit/Reporters/JsonV2SerializerTest.php
> GitHub actions

- tests/Unit/Propagation/TraceContextTest.php
- tests/Unit/TracerTest.php
> Reopen PR #188

- .github/workflows/ci.yml
- README.md
- tests/Unit/Reporters/JsonV2SerializerTest.php
This PR upgrades the coverage tool and decreases the number of builds.
Thanks to @peter279k
> chore(ci): tweaks coverage.

- src/Zipkin/Reporters/JsonV2Serializer.php
- tests/Integration/Reporters/Http/CurlFactoryTest.php
- tests/Unit/Reporters/JsonV2SerializerTest.php
Follows from https://github.com/Vinelab/tracing-laravel/pull/27#issuecomment-731280313
Ping @KinaneD @adiachenko
> fix(json-serializer): fixes serialization for strings including backslashes.

- .github/workflows/ci.yml
- composer.json
> Uses 3.0.x

- composer.json
- src/Zipkin/Propagation/ExtraField.php
- src/Zipkin/Propagation/TraceContext.php
- tests/Integration/Instrumentation/Mysqli/access.cnf
- tests/Unit/Propagation/ExtraFieldTest.php
- tests/Unit/Propagation/TraceContextTest.php
This PR adds support to the `ExtraFields` propagation based on https://github.com/openzipkin/brave/tree/master/brave#propagating-extra-fields
Closes #13
Ping @beberlei @adriancole
> Adds support to EXTRA propagation.

- src/Zipkin/Propagation/Map.php
strtolower(): Argument #1 ($string) must be of type string
> Convert carrier key to string.
